Traceback (most recent call last):
  File "./test_pycuda_con.py", line 4, in <module>
    import pycuda.autoinit
  File "/home/659/zxw659/.local/lib/python2.7/site-packages/pycuda-2012.1-py2.7-linux-x86_64.egg/pycuda/autoinit.py", line 4, in <module>
    cuda.init()
pycuda._driver.RuntimeError: cuInit failed: no device
